/**
 * Rikets kommuner som Prikko INTE täcker, som slug och namn.
 *
 * Används av 404-sidan och av ingenting annat. En besökare som skriver
 * prikko.se/goteborg/ eller följer en länk dit fick förut en generisk "Sidan
 * finns inte", trots att det enda sanna svaret är att vi inte täcker kommunen
 * än. 404-sidan läser adressens första led i webbläsaren och säger det, med
 * kvar statuskod 404 och utan en enda ny sida. Tunna sidor för kommuner utan
 * data vore precis de sidor som bara finns för sökmotorer, se
 * docs/prikko-sidor-bara-for-seo i minnet och bibelns kvalitetsgrind.
 *
 * VARFÖR EN INCHECKAD LISTA OCH INTE EN LÄSNING UR pipeline/data. Sajtbygget
 * läser ingenting ur pipeline/ i dag, och en 404-sida är fel ställe att börja.
 * Listan är genererad 2026-09-14 ur pipeline/data/kommuner.json (290 poster,
 * byggd av pipeline/fetch_kommuner.py) med exakt slugify() i lib/slug.ts.
 * Prövad mot sajtens egna slugar: alla 13 täckta kommuner gav samma slug.
 * EN krock finns bland 290: Håbo och Habo blir båda `habo`. Ingen av dem
 * täcks, och posten bär därför båda namnen i stället för att tyst välja ett,
 * för den som skrev /habo/ kan ha menat vilken som helst. Kommunindelningen ändras sällan och med års varsel.
 *
 * DEN MÅSTE GÅ OM NÄR EN KOMMUN TILLKOMMER PÅ SAJTEN, annars säger 404-sidan
 * "täcks inte" om en kommun som har sidor. Därför kontrollerar 404-sidan vid
 * bygget att ingen slug här också finns bland de täckta, och fäller bygget
 * om det händer.
 */
export const OTACKTA_KOMMUNER: ReadonlyArray<readonly [slug: string, namn: string]> = [
  ["ale", "Ale"],
  ["alingsas", "Alingsås"],
  ["almhult", "Älmhult"],
  ["alvdalen", "Älvdalen"],
  ["alvesta", "Alvesta"],
  ["alvkarleby", "Älvkarleby"],
  ["alvsbyn", "Älvsbyn"],
  ["amal", "Åmål"],
  ["aneby", "Aneby"],
  ["ange", "Ånge"],
  ["angelholm", "Ängelholm"],
  ["arboga", "Arboga"],
  ["are", "Åre"],
  ["arjang", "Årjäng"],
  ["arjeplog", "Arjeplog"],
  ["arvidsjaur", "Arvidsjaur"],
  ["arvika", "Arvika"],
  ["asele", "Åsele"],
  ["askersund", "Askersund"],
  ["astorp", "Åstorp"],
  ["atvidaberg", "Åtvidaberg"],
  ["avesta", "Avesta"],
  ["bastad", "Båstad"],
  ["bengtsfors", "Bengtsfors"],
  ["berg", "Berg"],
  ["bjurholm", "Bjurholm"],
  ["bjuv", "Bjuv"],
  ["boden", "Boden"],
  ["bollebygd", "Bollebygd"],
  ["bollnas", "Bollnäs"],
  ["boras", "Borås"],
  ["borlange", "Borlänge"],
  ["botkyrka", "Botkyrka"],
  ["boxholm", "Boxholm"],
  ["bracke", "Bräcke"],
  ["bromolla", "Bromölla"],
  ["burlov", "Burlöv"],
  ["dals-ed", "Dals-Ed"],
  ["danderyd", "Danderyd"],
  ["degerfors", "Degerfors"],
  ["dorotea", "Dorotea"],
  ["eda", "Eda"],
  ["ekero", "Ekerö"],
  ["eksjo", "Eksjö"],
  ["emmaboda", "Emmaboda"],
  ["enkoping", "Enköping"],
  ["eskilstuna", "Eskilstuna"],
  ["eslov", "Eslöv"],
  ["essunga", "Essunga"],
  ["fagersta", "Fagersta"],
  ["falkenberg", "Falkenberg"],
  ["falkoping", "Falköping"],
  ["falun", "Falun"],
  ["fargelanda", "Färgelanda"],
  ["filipstad", "Filipstad"],
  ["finspang", "Finspång"],
  ["flen", "Flen"],
  ["forshaga", "Forshaga"],
  ["gagnef", "Gagnef"],
  ["gallivare", "Gällivare"],
  ["gavle", "Gävle"],
  ["gislaved", "Gislaved"],
  ["gnesta", "Gnesta"],
  ["gnosjo", "Gnosjö"],
  ["goteborg", "Göteborg"],
  ["gotene", "Götene"],
  ["gotland", "Gotland"],
  ["grastorp", "Grästorp"],
  ["grums", "Grums"],
  ["gullspang", "Gullspång"],
  ["habo", "Habo eller Håbo"],
  ["hagfors", "Hagfors"],
  ["hallefors", "Hällefors"],
  ["hallsberg", "Hallsberg"],
  ["hallstahammar", "Hallstahammar"],
  ["halmstad", "Halmstad"],
  ["hammaro", "Hammarö"],
  ["haninge", "Haninge"],
  ["haparanda", "Haparanda"],
  ["harjedalen", "Härjedalen"],
  ["harnosand", "Härnösand"],
  ["harryda", "Härryda"],
  ["hassleholm", "Hässleholm"],
  ["heby", "Heby"],
  ["hedemora", "Hedemora"],
  ["helsingborg", "Helsingborg"],
  ["herrljunga", "Herrljunga"],
  ["hjo", "Hjo"],
  ["hofors", "Hofors"],
  ["hogsby", "Högsby"],
  ["hoor", "Höör"],
  ["horby", "Hörby"],
  ["huddinge", "Huddinge"],
  ["hudiksvall", "Hudiksvall"],
  ["hultsfred", "Hultsfred"],
  ["hylte", "Hylte"],
  ["jarfalla", "Järfälla"],
  ["jokkmokk", "Jokkmokk"],
  ["kalix", "Kalix"],
  ["kalmar", "Kalmar"],
  ["karlsborg", "Karlsborg"],
  ["karlshamn", "Karlshamn"],
  ["karlskoga", "Karlskoga"],
  ["karlskrona", "Karlskrona"],
  ["katrineholm", "Katrineholm"],
  ["kavlinge", "Kävlinge"],
  ["kil", "Kil"],
  ["kinda", "Kinda"],
  ["kiruna", "Kiruna"],
  ["klippan", "Klippan"],
  ["knivsta", "Knivsta"],
  ["koping", "Köping"],
  ["kramfors", "Kramfors"],
  ["kristianstad", "Kristianstad"],
  ["krokom", "Krokom"],
  ["kumla", "Kumla"],
  ["kungalv", "Kungälv"],
  ["kungsbacka", "Kungsbacka"],
  ["kungsor", "Kungsör"],
  ["laholm", "Laholm"],
  ["landskrona", "Landskrona"],
  ["laxa", "Laxå"],
  ["lekeberg", "Lekeberg"],
  ["leksand", "Leksand"],
  ["lerum", "Lerum"],
  ["lessebo", "Lessebo"],
  ["lidingo", "Lidingö"],
  ["lidkoping", "Lidköping"],
  ["lilla-edet", "Lilla Edet"],
  ["lindesberg", "Lindesberg"],
  ["ljungby", "Ljungby"],
  ["ljusdal", "Ljusdal"],
  ["ljusnarsberg", "Ljusnarsberg"],
  ["ludvika", "Ludvika"],
  ["lulea", "Luleå"],
  ["lund", "Lund"],
  ["lycksele", "Lycksele"],
  ["lysekil", "Lysekil"],
  ["mala", "Malå"],
  ["malmo", "Malmö"],
  ["malung-salen", "Malung-Sälen"],
  ["mariestad", "Mariestad"],
  ["mark", "Mark"],
  ["markaryd", "Markaryd"],
  ["mellerud", "Mellerud"],
  ["mjolby", "Mjölby"],
  ["molndal", "Mölndal"],
  ["monsteras", "Mönsterås"],
  ["mora", "Mora"],
  ["morbylanga", "Mörbylånga"],
  ["motala", "Motala"],
  ["mullsjo", "Mullsjö"],
  ["munkedal", "Munkedal"],
  ["munkfors", "Munkfors"],
  ["nacka", "Nacka"],
  ["nassjo", "Nässjö"],
  ["nora", "Nora"],
  ["norberg", "Norberg"],
  ["nordanstig", "Nordanstig"],
  ["nordmaling", "Nordmaling"],
  ["norrtalje", "Norrtälje"],
  ["norsjo", "Norsjö"],
  ["nybro", "Nybro"],
  ["nykoping", "Nyköping"],
  ["nykvarn", "Nykvarn"],
  ["nynashamn", "Nynäshamn"],
  ["ockelbo", "Ockelbo"],
  ["ockero", "Öckerö"],
  ["odeshog", "Ödeshög"],
  ["olofstrom", "Olofström"],
  ["orkelljunga", "Örkelljunga"],
  ["ornskoldsvik", "Örnsköldsvik"],
  ["orsa", "Orsa"],
  ["orust", "Orust"],
  ["osby", "Osby"],
  ["osteraker", "Österåker"],
  ["ostersund", "Östersund"],
  ["osthammar", "Östhammar"],
  ["ostra-goinge", "Östra Göinge"],
  ["ovanaker", "Ovanåker"],
  ["overkalix", "Överkalix"],
  ["overtornea", "Övertorneå"],
  ["oxelosund", "Oxelösund"],
  ["pajala", "Pajala"],
  ["partille", "Partille"],
  ["perstorp", "Perstorp"],
  ["pitea", "Piteå"],
  ["ragunda", "Ragunda"],
  ["rattvik", "Rättvik"],
  ["robertsfors", "Robertsfors"],
  ["ronneby", "Ronneby"],
  ["saffle", "Säffle"],
  ["sala", "Sala"],
  ["salem", "Salem"],
  ["sandviken", "Sandviken"],
  ["sater", "Säter"],
  ["savsjo", "Sävsjö"],
  ["sigtuna", "Sigtuna"],
  ["simrishamn", "Simrishamn"],
  ["sjobo", "Sjöbo"],
  ["skara", "Skara"],
  ["skelleftea", "Skellefteå"],
  ["skinnskatteberg", "Skinnskatteberg"],
  ["skovde", "Skövde"],
  ["skurup", "Skurup"],
  ["smedjebacken", "Smedjebacken"],
  ["soderhamn", "Söderhamn"],
  ["soderkoping", "Söderköping"],
  ["sodertalje", "Södertälje"],
  ["solleftea", "Sollefteå"],
  ["sollentuna", "Sollentuna"],
  ["solna", "Solna"],
  ["solvesborg", "Sölvesborg"],
  ["sorsele", "Sorsele"],
  ["sotenas", "Sotenäs"],
  ["staffanstorp", "Staffanstorp"],
  ["stenungsund", "Stenungsund"],
  ["storfors", "Storfors"],
  ["storuman", "Storuman"],
  ["strangnas", "Strängnäs"],
  ["stromstad", "Strömstad"],
  ["stromsund", "Strömsund"],
  ["sundbyberg", "Sundbyberg"],
  ["sundsvall", "Sundsvall"],
  ["sunne", "Sunne"],
  ["surahammar", "Surahammar"],
  ["svalov", "Svalöv"],
  ["svedala", "Svedala"],
  ["taby", "Täby"],
  ["tanum", "Tanum"],
  ["tibro", "Tibro"],
  ["tidaholm", "Tidaholm"],
  ["tierp", "Tierp"],
  ["timra", "Timrå"],
  ["tingsryd", "Tingsryd"],
  ["tjorn", "Tjörn"],
  ["tomelilla", "Tomelilla"],
  ["toreboda", "Töreboda"],
  ["torsas", "Torsås"],
  ["torsby", "Torsby"],
  ["tranas", "Tranås"],
  ["tranemo", "Tranemo"],
  ["trelleborg", "Trelleborg"],
  ["trollhattan", "Trollhättan"],
  ["trosa", "Trosa"],
  ["tyreso", "Tyresö"],
  ["uddevalla", "Uddevalla"],
  ["ulricehamn", "Ulricehamn"],
  ["umea", "Umeå"],
  ["upplands-bro", "Upplands-Bro"],
  ["upplands-vasby", "Upplands Väsby"],
  ["uppvidinge", "Uppvidinge"],
  ["vadstena", "Vadstena"],
  ["vaggeryd", "Vaggeryd"],
  ["valdemarsvik", "Valdemarsvik"],
  ["vallentuna", "Vallentuna"],
  ["vanersborg", "Vänersborg"],
  ["vannas", "Vännäs"],
  ["vansbro", "Vansbro"],
  ["vara", "Vara"],
  ["varberg", "Varberg"],
  ["vargarda", "Vårgårda"],
  ["varmdo", "Värmdö"],
  ["varnamo", "Värnamo"],
  ["vasteras", "Västerås"],
  ["vastervik", "Västervik"],
  ["vaxholm", "Vaxholm"],
  ["vaxjo", "Växjö"],
  ["vellinge", "Vellinge"],
  ["vetlanda", "Vetlanda"],
  ["vilhelmina", "Vilhelmina"],
  ["vimmerby", "Vimmerby"],
  ["vindeln", "Vindeln"],
  ["vingaker", "Vingåker"],
  ["ydre", "Ydre"],
  ["ystad", "Ystad"],
];
